title: JarrodRose[DOT]com
description: A boring website for a boring person.
theme: just-the-docs

url: https://jarrodrose.github.io

aux_links:
  Template Repository: https://github.com/jarrodrose/jarrodrose.github.io

heading_anchors: true

permalink: pretty

footer_content: "&copy; 2025 Jarrod Rose"
